<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.10deb1 setup script
 * Date: Sat, 14 Jan 2017 17:32:51 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: rdsstrn [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'rdsstrn';
$cfg['Servers'][$i]['host'] = 'cmp3.c8ohkabmwm3n.us-east-1.rds.amazonaws.com';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '587a6029cb3617.60510124';
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
?>